Refactor & YAML
Infocyte/extensions pull request #30
Opened 2020-12-14 23:18 UTC by singlethreaded

Big refactor.
-- Combined a lot of enhancements
-- Usability improvement with variables
-- Moved from TOML to YAML for readability and conformity

Everything works on my boxes. Needs additional testing due to so many changes

2020-12-14 23:38 UTC, timgit requested changes

2020-12-14 23:38 UTC, timgit commented on examples/enablevss.lua
> +created: 20191008
non-standard date formats here. We should probably keep this in the format like others just in case we parse this one day, I'm thinking.

2020-12-14 23:38 UTC, timgit commented on official/response/reboot.lua
> +local test = hunt.global.boolean("test", false, true)
what's the semantic difference between debug and test across all extensions?

2020-12-14 23:38 UTC, timgit commented on official/utilities/duplicatecontrollers.lua
>  --[=[
I don't think we should have this as an "official" extension

2020-12-19 16:27 UTC, singlethreaded commented on official/response/reboot.lua
> +local test = hunt.global.boolean("test", false, true)
debug = more verbose output
test = what the script does in my automated test suite

I hide test from the input documentation. Also switched debug to verbose. debug is a variable that the agent sometimes defines and exposes to the lua script... not sure why.

2020-12-19 16:27 UTC, singlethreaded commented on official/utilities/duplicatecontrollers.lua
>  --[=[
deleted

2020-12-19 16:27 UTC, singlethreaded commented on examples/enablevss.lua
> +created: 20191008
fixed

2020-12-19 16:37 UTC, rustysec commented on official/response/reboot.lua
> +local test = hunt.global.boolean("test", false, true)
it always exposes `debug` as that is the lua debug library which is needed for several runtime features, such as the precious string interpolation functions.

2020-12-29 00:10 UTC, singlethreaded commented
Im planning to merge this. tests are coming out good. The response extensions probably need the most TLC on expanded tests due to my inability to just loop them in my automated tests

2020-12-29 18:10 UTC, merged